# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dIPBH <- function(x, alpha, eta, log_transform = FALSE) {
    .Call(`_IPBH_dIPBH`, x, alpha, eta, log_transform)
}

pIPBH <- function(x, alpha, eta, lower_tail = TRUE, log_p = FALSE) {
    .Call(`_IPBH_pIPBH`, x, alpha, eta, lower_tail, log_p)
}

qIPBH <- function(p, alpha, eta, lower_tail = TRUE, log_p = FALSE) {
    .Call(`_IPBH_qIPBH`, p, alpha, eta, lower_tail, log_p)
}

rIPBH <- function(n, alpha, eta) {
    .Call(`_IPBH_rIPBH`, n, alpha, eta)
}

